FROM nginx:1.27.0

RUN sed -i -e 's/user www-data;/user www;/g' /etc/nginx/nginx.conf

RUN sed -i -e 's/user nginx;/user root;/g' /etc/nginx/nginx.conf

COPY . /var/www/html
#COPY ./deployment /var/www/html/api/deployment
RUN chmod -R 777 /var/www/

COPY ./deployment/nginx/conf.d/www.conf /etc/nginx/conf.d/default.conf
#EXPOSE 3002
ENTRYPOINT ["nginx", "-g", "daemon off;"]