# Use PHP 8.3 FPM
FROM php:8.3-fpm

ENV UID=1000
ENV GID=1000

RUN addgroup --gid 1000 www && adduser --uid 1000 --gid 1000 --home /home/www --disabled-password --gecos "" www

# Install system dependencies, PHP extensions, and Composer
RUN apt-get clean && apt-get update && apt-get install -y \
    libpq-dev \
    zlib1g-dev \
    unzip \
    p7zip-full \
    libzip-dev \
    libicu-dev \
    curl \
    libssl-dev \
    pkg-config \
    libpng-dev \
    zip \
    libxml2-dev \
    libonig-dev \
    libxslt-dev \
    # Install Node.js and npm
    nodejs \
    npm \
    # Install PHP extensions
    && docker-php-ext-install intl \
    && docker-php-ext-configure zip \
    && docker-php-ext-install zip \
    && docker-php-ext-install pdo_pgsql \
    && docker-php-ext-install pdo_mysql \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && docker-php-ext-install pcntl


# Set working directory
WORKDIR /var/www/html

# Ensure correct ownership for the application files
#RUN chown -R www:www /var/www/html

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Copy application code first to avoid invalidating cache unnecessarily
COPY . /var/www/html

# Change current user to www
USER www

# Set entrypoint
ENTRYPOINT ["sh", "/var/www/html/deployment/php/entrypoint.sh"]
